#!/usr/bin/env bash
# Nginx installation: remote server

sudo apt -y update
sudo apt -y install nginx
# Firewall port 80
sudo ufw allow 'Nginx HTTP'
# Fix permission problems on folder, grant access to ubuntu group Ubuntu 20.04
sudo chgrp -R ubuntu /usr/share/nginx/html
sudo chmod -R g+w /usr/share/nginx/html
# Index file and start
sudo echo 'Hello World' | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start
