#!/usr/bin/env bash
# Nginx installation: remote server
# Create 404 response page

sudo apt-get -y update
sudo apt-get -y install nginx
# Firewall port 80
sudo ufw allow 'Nginx HTTP'
# Fix permission problems on folder, grant access to ubuntu group Ubuntu 14.04
sudo chgrp -R ubuntu /var/www/html
# sudo chgrp -R ubuntu /etc/nginx/sites-available/default
sudo chmod -R g+w /var/www/html
# sudo chmod -R g+w /etc/nginx/sites-available/default
# Index file
sudo echo 'Hello World' | sudo tee /var/www/html/index.nginx-debian.html
# Edit configuration file? stop the service!
sudo service nginx stop
# Redirection
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n' /etc/nginx/sites-available/default
#404 
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
sudo sed -i '/listen 80 default_server/a error_page 404 /custom_404.html;location = /custom_404.html {root /var/www/html;\n internal;}' /etc/nginx/sites-available/default
# Restart
sudo service nginx restart
