#!/usr/bin/env bash
#comment

sudo apt update -y
sudo apt install -y nginx
sudo chmod -R 777 /var/www/html
sudo echo "Hello World" | sudo tee /var/www/html/index.html
sudo /etc/init.d/nginx stop
sudo sed -i '/server_name _;/a rewrite ^/redirect_me https://https://www.youtube.com/watch?v=QH2-TGUlwu4/$1 permanent;' /etc/nginx/sites-available/default
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom.html
sudo sed -i '/server_name _;/a error_page 404 /custom.html;' /etc/nginx/sites-available/default
var=$(cat /proc/sys/kernel/hostname)
sudo sed -i '/http {/a add_header X-Served-By '"${var}"';' /etc/nginx/nginx.conf
sudo /etc/init.d/nginx start
