#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a
# custom header (on web-01 and web-02)

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
# Permissions
sudo chgrp -R ubuntu /var/www/html
sudo chmod -R g+w /var/www/html
# Create Files
sudo echo "Hello World" | sudo tee /var/www/html/index.html
#404 
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
# Edit configuration file? stop the service!
sudo service nginx stop
# Redirection
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n' /etc/nginx/sites-available/default
#NGINX trial
sudo sed -i "/http {/a add_header X-Served-By \"$HOSTNAME\";" /etc/nginx/nginx.conf
sudo sed -i '/server_name _;/a error_page 404 /custom_404.html;' /etc/nginx/sites-available/default
sudo service nginx start
