#!/usr/bin/env bash
# Configure web servers for load balancer - HAPROXY 

sudo apt update &&
sudo apt install -y haproxy
# Backup basic configuration
EPOCH=$(date +%s)
cp /etc/haproxy/haproxy.cfg ./haproxy."$EPOCH".cfg
# Enable HAPROXY
echo "ENABLED=1" >> /etc/default/haproxy
# Write config
cat >> /etc/haproxy/haproxy.cfg << EOF
listen http-in
        bind *:80
        mode http
        balance roundrobin
        server 4434-web-01 54.162.164.215:80 check
        server 4434-web-02 54.221.24.84:80 check
EOF
# Create Files
service haproxy restart
