#!/usr/bin/env bash
# Script that displays Best School 10 times,
# but for the 9th iteration, displays Best
#School and then Hi on a new line

I=0
while((I<10))
do
	echo "Best School"
	if((I == 8))
	then
		echo "Hi"
	fi
	((I++))
done

