#!/usr/bin/env bash
#Bash script that configures an Ubuntu 
#server with the below requirements

cp /etc/hosts ~/hosts.new
sed -i '/localhost/s/127.0.0.[1-9]/127.0.0.2/' ~/hosts.new
echo -e "\n8.8.8.8\tfacebook.com">> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
